
---
server:
  port: "8891"
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tejakathari007/go-deliver.properties.git
  application:
    name: configserver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: "true"
    fetch-registry: "true"
...
