# Loco yaml export: Symfony YAML object
# Project: userprofile.properties conversion
# Release: Working copy
# Locale: en-GB, English (UK)
# Exported by: Unregistered user
# Exported at: Thu, 30 Aug 2018 17:48:42 +0530
---
spring:
  application:
    name: userprofile
  data:
    mongodb:
      database: userprofile
      host: localhost
      password: ""
      port: "27017"
      uri: mongodb://localhost/userprofile
      username: ""
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-uri:
      defaultzone: http://8761/eureka
...
