version: '2.1'
services:
  eureka-server:
    build: eureka-server/
    depends_on:
      config-service:
        condition: service_healthy
    restart: always
    network_mode: "host"
    image: demo-eureka-service
    hostname: localhost
    ports:
      - 8761:8761
    healthcheck:
      test: "exit 0"

  config-service:
    build: config-service/
    restart: always
    network_mode: "host"
    image: demo-config-service
    hostname: localhost
    ports:
      - 8891:8891
    healthcheck:
      test: "exit 0"

  mysql:
    image: mysql:5.5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go_d
      - MYSQL_PASSWORD=
    network_mode: "host"
    hostname: localhost
    restart: always
    healthcheck:
      test: "exit 0"


  user-login:
    build: user-login/
    container_name: user-login-docker
    depends_on:
      - mysql
    healthcheck:
      test: exit 0
    hostname: localhost
    image: user-login
    network_mode: host
    ports:
      - 8082:8082
    restart: always

#user-profile:
#   image: 14052831/userprofile:1.0
#   restart: always
#   network_mode: host
#   container_name: spring-docker
#   depends_on:
#       - mongo
#   ports:
#      - 8070:8070
      
      

       

