# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
 
  - job_name: 'prometheus'
    static_configs:
    - targets: ['172.23.239.49:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['172.23.239.49:3000']

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.100:8761']

  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.100:8080']
    
  - job_name: 'config-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.100:8891']

  - job_name: 'user-profile'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.114:8070'] 

  - job_name: 'book-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.114:8888']

  - job_name: 'recommendation'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.114:8092']

  - job_name: 'user-login'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.114:8082']
    
  - job_name: 'order-details'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.121:8081']
    
  - job_name: 'logistics-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.121:8086']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.123:8086']

  - job_name: 'cvrp-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['172.23.239.123:8086']
