port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/go_d?useSSL=false
    username: root
    password: Root@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
