# Loco yaml export: Symfony YAML object
# Project: api-gateway.properties conversion
# Release: Working copy
# Locale: en-GB, English (UK)
# Exported by: Unregistered user
# Exported at: Thu, 30 Aug 2018 17:47:00 +0530
---
spring:
  application:
    name: api-gateway
zuul:
  routes:
    userprofile:
      url: http://localhost:8070
    book:
      url: http://localhost:8888
    user-login:
      url: http://localhost:8082
    recommendation:
      url: http://localhost:8092
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    serviceUrl:
      defaultZone: http://8761/eureka
...
