
---
spring:
  application:
    name: book
  data:
    mongodb:
      database: booksdb
      host: mongodatabase
      password: root1234
      port: "27018"
      uri: mongodb://mongodatabase/booksdb
      username: admin
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-uri:
      defaultzone: http://8761/eureka
...
