
---
spring:
  application:
    name: userprofile
  data:
    mongodb:
      database: userprofile
      host: localhost
      password: ""
      port: "27017"
      uri: mongodb://localhost/userprofile
      username: ""
eureka:
  client:
    register-with-eureka: "true"
    fetch-registry: "true"
    service-uri:
      defaultzone: http://8761/eureka
...
